[package]
edition = "2021"
name = "copland_os"
version = "0.0.1"

[dependencies]
hashbrown = "0.12.0"
log = "0.4.17"
spin = "0.9.2"
volatile = "0.3.0"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.4.0"

[build-dependencies]
toml = "0.5.9"
