[env]
ARCH = "default"
BIN = "kernel.elf"
BOARD = "default"
CORE = "1"
DISK = "disk.img"
MODE = "debug"

[tasks.make-disk]
script = '''
touch $DISK
'''

[tasks.build]
script = '''
if [ $ARCH = "default" ]; then
    if [ $MODE = "release" ]; then
        cargo build --release
    else
        cargo build
    fi
else
    if [ $MODE = "release" ]; then
        cargo build --target $ARCH --release
    else
        cargo build --target $ARCH
    fi
fi

cp ./target/$ARCH/$MODE/copland_os $BIN
'''
[tasks.build-riscv64-dev]
env = {ARCH = "riscv64gc-unknown-none-elf", MODE = "debug"}
run_task = "build"

[tasks.build-riscv64]
env = {ARCH = "riscv64gc-unknown-none-elf", MODE = "release"}
run_task = "build"

[tasks.build-aarch64-dev]
env = {ARCH = "aarch64-unknown-none-softfloat", MODE = "debug"}
run_task = "build"

[tasks.build-aarch64]
env = {ARCH = "aarch64-unknown-none-softfloat", MODE = "release"}
run_task = "build"

[tasks.run-riscv64-dev]
dependencies = ["build-riscv64-dev", "make-disk"]
script = '''
qemu-system-riscv64 -s -machine virt -bios none -m 256M -smp $CORE -serial stdio -kernel $BIN \
    -drive file=$DISK,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0
'''

[tasks.run-riscv64]
dependencies = ["build-riscv64", "make-disk"]
script = '''
qemu-system-riscv64 -machine virt -bios none -m 256M -smp $CORE -serial stdio -kernel $BIN \
    -drive file=$DISK,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0
'''

[tasks.run-aarch64-dev]
dependencies = ["build-aarch64-dev"]
script = '''
qemu-system-aarch64 -s -machine raspi3b -m 1G -serial null -serial stdio -kernel $BIN
'''

[tasks.run-aarch64]
dependencies = ["build-aarch64"]
script = '''
qemu-system-aarch64 -machine raspi3b -m 1G -serial null -serial stdio -kernel $BIN
'''

[tasks.debug-riscv64]
dependencies = ["build-riscv64-dev", "make-disk"]
script = '''
qemu-system-riscv64 -s -S -machine virt -bios none -m 256M -smp $CORE -serial stdio -kernel $BIN \
    -drive file=$DISK,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0
'''

[tasks.debug-aarch64]
dependencies = ["build-aarch64-dev"]
script = '''
qemu-system-aarch64 -s -S -machine raspi3b -m 1G -serial null -serial stdio -kernel $BIN
'''

[tasks.clean]
script = '''
rm -rf $BIN $DISK
cargo clean
'''

[config]
skip_core_tasks = true
