[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -bios none -m 256M -smp 1 -serial stdio -kernel "
rustflags = [
  "-Clink-args=-Tlinker/virt.ld",
]

[target.aarch64-unknown-none-softfloat]
runner = "qemu-system-aarch64 -machine raspi3b -m 1G -kernel "
rustflags = [
  "-Clink-args=-Tlinker/raspi3b.ld",
]
